### ISSUE TITLE
Does the project support Mitsubishi Electric MSZ-HR35

### ISSUE THREAD

**Issue by Dataaja95** [geoffdavis/esphome-mitsubishiheatpump#149]
The heat pump in question is only for cooling model, whether the project supports the hardware in question.

**Comment by txitxo0** [comment]
Interested in MSZ-HR series, up!

**Comment by txitxo0** [comment]
@Dataaja95 as long as I understood, this project is using the library swicago.

In this repo there are some people sharing their feedback:

https://github.com/SwiCago/HeatPump/issues/13#issuecomment-2069843041

https://github.com/SwiCago/HeatPump/issues/13#issuecomment-2045607200

https://github.com/SwiCago/HeatPump/issues/13#issuecomment-1849987380

**Comment by Dataaja95** [comment]
@txitxo0 Thanks for this, apparently the pump in question is supported.
