### ISSUE TITLE
Vane position not present

### ISSUE THREAD

**Issue by jamescadd** [geoffdavis/esphome-mitsubishiheatpump#18]
Vane swing mode works on MS-GL09NA, but I don't see an option for vane position in Home Assistant in the details card.  Is it possible to add this or is it an ESPHome limitation?

**Comment by jamescadd** [comment]
@geoffdavis any guidance on whether this could be possible, or maybe is it missing from the underlying library?

**Comment by geoffdavis** [comment]
I believe it's an ESPHOME limitation - there isn't currently any provision for custom vane positions, though home assistant does support it.

**Comment by ipetrovits** [comment]
Hi, Will this issue resolved by https://github.com/home-assistant/core/pull/44495 in HA 2021.2.1 ?

**Comment by pgenera** [comment]
I believe there also has to be a matching esphome release.

**Comment by jamescadd** [comment]
Sadly the comment referencing a new PR was for fan direction, either forward or reverse, not vane position.
