### ISSUE TITLE
Library no longer needs dev version of ESPhome

### ISSUE THREAD

**Issue by geoffdavis** [geoffdavis/esphome-mitsubishiheatpump#22]
ESPhome 0.15.1 is out and with it the extra states that this library uses. The README and installation instructions should be updated.

**Comment by jamescadd** [comment]
Hi Geoff, could you provide a couple of tips on moving from the dev version of ESPHome to 0.15.1 or greater?  I can submit a PR to update the readme if you give some pointers.

**Comment by geoffdavis** [comment]
Just compile the same yaml files under the normal version of ESPHome, and it will just work with no changes.

**Comment by geoffdavis** [comment]
I fixed this earlier today in commit https://github.com/geoffdavis/esphome-mitsubishiheatpump/commit/7a18097fb7a89807e830935f4d2300bbec8ce9d3
