### ISSUE TITLE
Incompatibilities with ESPHome > 1.19.0

### ISSUE THREAD

**Issue by jesserockz** [geoffdavis/esphome-mitsubishiheatpump#37]
https://www.github.com/geoffdavis/esphome-mitsubishiheatpump/tree/master/components%2Fmitsubishi_heatpump%2Fespmhp.cpp#L144

ESPHome has changed AUTO to HEAT_COOL

AUTO still exists, but it now has a new meaning and should not be used until AUTO support for ESPHome is added to Home Assistant

**Comment by geoffdavis** [comment]
Fixed in GH-38
