### ISSUE TITLE
HeatPump reverts to cooling unexpectedly

### ISSUE THREAD

**Issue by jamescadd** [geoffdavis/esphome-mitsubishiheatpump#45]
A couple of weeks ago we started needing heat in Seattle, up until then I'd been running the MSZ-GL09NA head units (3 of them) on cool mode all summer without issue.  I've made it a rule to generally avoid auto mode as I like to manually choose heat or cool.

After changing them to heat mode with the Home Assistant UI (using the simple thermostat lovelace element from HACS) they begin blowing hot air.  However at some point after this, it could be several hours, they revert to cool mode and start blowing very cold air.  I have yet to repro and manually review the logs at this time but will update when I do.

I have also tried turning the head unit to heat with the remote and not touching Home Assistant, but with the same result that it ends up blowing cold air at some later point, possibly hours after I set it to heat.  I've never had them turn on by themselves, this only happens once I've started them in heat mode.

Side note: In the logs for a couple of the head units I've noticed that the "saved auto" temp is set to -1.  I wouldn't have manually intended to set them so low but I also don't know how to force that value (with HA or a remote) to be something more reasonable to rule it out.

Disclaimer: I'm filing this under the "so strange I must be doing something wrong" category and hoping to update the issue with an embarrassing story about IR from my Harmony remote doing something strange to the head unit.  I am also not on the latest ESPHome as I stayed on 2021.9.3 after seeing the issues compiling with newer versions (Home Assistant & OS are up to date).

**Comment by jamescadd** [comment]
I can close this out now - it was a failed reversing valve in the unit.  It would go into defrost mode from heat, and then get stuck there and basically be on cool mode.

**Comment by geoffdavis** [comment]
Glad to hear you figured it out - I was at a loss as mine don't seem to exhibit this behavior (yet.)
