### ISSUE TITLE
Double declaration of delay() function

### ISSUE THREAD

**Issue by F43RY** [geoffdavis/esphome-mitsubishiheatpump#47]
Hi,
I tried to upgrade esphome to latest release in my esp01 in my heatpump by I got issues at compile time.
I deleted old folder with old files but the issue came up again. Here below the full log of esphome dashboard.
No issues with past release of esphome.
I think the issue is a conflict due to a double declaration of function delay() in two different librearies.

`INFO Reading configuration ./heatpump_camera.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing heatpump-camera (board: esp01_1m; framework: arduino; platform: platformio/espressif8266 @ 2.6.2)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Library Manager: Installing ottowinter/ESPAsyncTCP-esphome @ 1.2.3

Downloading  [------------------------------------]    0%
Downloading  [#######-----------------------------]   20%
Downloading  [##############----------------------]   40%
Downloading  [#####################---------------]   60%
Downloading  [############################--------]   80%
Downloading  [####################################]  100%

Unpacking  [------------------------------------]    0%
Unpacking  [#-----------------------------------]    3%
Unpacking  [##----------------------------------]    6%
Unpacking  [###---------------------------------]    9%
Unpacking  [####--------------------------------]   12%
Unpacking  [#####-------------------------------]   15%
Unpacking  [######------------------------------]   18%
Unpacking  [#######-----------------------------]   21%
Unpacking  [#########---------------------------]   25%
Unpacking  [##########--------------------------]   28%
Unpacking  [###########-------------------------]   31%
Unpacking  [############------------------------]   34%
Unpacking  [#############-----------------------]   37%
Unpacking  [##############----------------------]   40%
Unpacking  [###############---------------------]   43%
Unpacking  [################--------------------]   46%
Unpacking  [##################------------------]   50%
Unpacking  [###################-----------------]   53%
Unpacking  [####################----------------]   56%
Unpacking  [#####################---------------]   59%
Unpacking  [######################--------------]   62%
Unpacking  [#######################-------------]   65%
Unpacking  [########################------------]   68%
Unpacking  [#########################-----------]   71%
Unpacking  [###########################---------]   75%
Unpacking  [############################--------]   78%
Unpacking  [#############################-------]   81%
Unpacking  [##############################------]   84%
Unpacking  [###############################-----]   87%
Unpacking  [################################----]   90%
Unpacking  [#################################---]   93%
Unpacking  [##################################--]   96%
Unpacking  [####################################]  100%
Library Manager: ESPAsyncTCP-esphome @ 1.2.3 has been installed!
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 2.0.0

Unpacking  [------------------------------------]    0%
Unpacking  [#-----------------------------------]    2%
Unpacking  [##----------------------------------]    5%
Unpacking  [###---------------------------------]    8%
Unpacking  [####--------------------------------]   11%
Unpacking  [#####-------------------------------]   14%
Unpacking  [######------------------------------]   17%
Unpacking  [#######-----------------------------]   20%
Unpacking  [########----------------------------]   22%
Unpacking  [#########---------------------------]   25%
Unpacking  [##########--------------------------]   28%
Unpacking  [###########-------------------------]   31%
Unpacking  [############------------------------]   34%
Unpacking  [#############-----------------------]   37%
Unpacking  [##############----------------------]   40%
Unpacking  [###############---------------------]   42%
Unpacking  [################--------------------]   45%
Unpacking  [#################-------------------]   48%
Unpacking  [##################------------------]   51%
Unpacking  [###################-----------------]   54%
Unpacking  [####################----------------]   57%
Unpacking  [#####################---------------]   60%
Unpacking  [######################--------------]   62%
Unpacking  [#######################-------------]   65%
Unpacking  [########################------------]   68%
Unpacking  [#########################-----------]   71%
Unpacking  [##########################----------]   74%
Unpacking  [###########################---------]   77%
Unpacking  [############################--------]   80%
Unpacking  [#############################-------]   82%
Unpacking  [##############################------]   85%
Unpacking  [###############################-----]   88%
Unpacking  [################################----]   91%
Unpacking  [#################################---]   94%
Unpacking  [##################################--]   97%
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer-esphome @ 2.0.0 has been installed!
Library Manager: Installing dependencies...
Library Manager: ESPAsyncTCP-esphome @ 1.2.3 is already installed
Library Manager: Installing esphome/AsyncTCP-esphome

Unpacking  [------------------------------------]    0%
Unpacking  [##----------------------------------]    6%
Unpacking  [####--------------------------------]   12%
Unpacking  [######------------------------------]   18%
Unpacking  [#########---------------------------]   25%
Unpacking  [###########-------------------------]   31%
Unpacking  [#############-----------------------]   37%
Unpacking  [###############---------------------]   43%
Unpacking  [##################------------------]   50%
Unpacking  [####################----------------]   56%
Unpacking  [######################--------------]   62%
Unpacking  [########################------------]   68%
Unpacking  [###########################---------]   75%
Unpacking  [#############################-------]   81%
Unpacking  [###############################-----]   87%
Unpacking  [#################################---]   93%
Unpacking  [####################################]  100%
Library Manager: AsyncTCP-esphome @ 1.2.2 has been installed!
Library Manager: Installing Hash
Library Manager: Installing ottowinter/AsyncMqttClient-esphome @ 0.8.6

Unpacking  [------------------------------------]    0%
Unpacking  [------------------------------------]    2%
Unpacking  [#-----------------------------------]    4%
Unpacking  [##----------------------------------]    6%
Unpacking  [###---------------------------------]    9%
Unpacking  [####--------------------------------]   11%
Unpacking  [#####-------------------------------]   13%
Unpacking  [#####-------------------------------]   16%
Unpacking  [######------------------------------]   18%
Unpacking  [#######-----------------------------]   20%
Unpacking  [########----------------------------]   23%
Unpacking  [#########---------------------------]   25%
Unpacking  [##########--------------------------]   27%
Unpacking  [##########--------------------------]   30%
Unpacking  [###########-------------------------]   32%
Unpacking  [############------------------------]   34%
Unpacking  [#############-----------------------]   37%
Unpacking  [##############----------------------]   39%
Unpacking  [###############---------------------]   41%
Unpacking  [###############---------------------]   44%
Unpacking  [################--------------------]   46%
Unpacking  [#################-------------------]   48%
Unpacking  [##################------------------]   51%
Unpacking  [###################-----------------]   53%
Unpacking  [####################----------------]   55%
Unpacking  [####################----------------]   58%
Unpacking  [#####################---------------]   60%
Unpacking  [######################--------------]   62%
Unpacking  [#######################-------------]   65%
Unpacking  [########################------------]   67%
Unpacking  [#########################-----------]   69%
Unpacking  [#########################-----------]   72%
Unpacking  [##########################----------]   74%
Unpacking  [###########################---------]   76%
Unpacking  [############################--------]   79%
Unpacking  [#############################-------]   81%
Unpacking  [##############################------]   83%
Unpacking  [##############################------]   86%
Unpacking  [###############################-----]   88%
Unpacking  [################################----]   90%
Unpacking  [#################################---]   93%
Unpacking  [##################################--]   95%
Unpacking  [###################################-]   97%
Unpacking  [####################################]  100%
Library Manager: AsyncMqttClient-esphome @ 0.8.6 has been installed!
Library Manager: Installing dependencies...
Library Manager: ESPAsyncTCP-esphome @ 1.2.3 is already installed
Library Manager: AsyncTCP-esphome @ 1.2.2 is already installed
Library Manager: Installing ottowinter/ArduinoJson-esphomelib @ 5.13.3

Downloading  [------------------------------------]    0%
Downloading  [#####-------------------------------]   14%
Downloading  [##########--------------------------]   28%
Downloading  [###############---------------------]   42%
Downloading  [####################----------------]   57%
Downloading  [#########################-----------]   71%
Downloading  [##############################------]   85%
Downloading  [####################################]  100%

Unpacking  [------------------------------------]    0%
Unpacking  [------------------------------------]    1%
Unpacking  [------------------------------------]    2%
Unpacking  [#-----------------------------------]    3%
Unpacking  [#-----------------------------------]    4%
Unpacking  [##----------------------------------]    5%
Unpacking  [##----------------------------------]    6%
Unpacking  [##----------------------------------]    7%
Unpacking  [##----------------------------------]    8%
Unpacking  [###---------------------------------]    8%
Unpacking  [###---------------------------------]    9%
Unpacking  [###---------------------------------]   10%
Unpacking  [####--------------------------------]   11%
Unpacking  [####--------------------------------]   12%
Unpacking  [####--------------------------------]   13%
Unpacking  [#####-------------------------------]   14%
Unpacking  [#####-------------------------------]   15%
Unpacking  [#####-------------------------------]   16%
Unpacking  [######------------------------------]   16%
Unpacking  [######------------------------------]   17%
Unpacking  [######------------------------------]   18%
Unpacking  [######------------------------------]   19%
Unpacking  [#######-----------------------------]   20%
Unpacking  [#######-----------------------------]   21%
Unpacking  [########----------------------------]   22%
Unpacking  [########----------------------------]   23%
Unpacking  [########----------------------------]   24%
Unpacking  [#########---------------------------]   25%
Unpacking  [#########---------------------------]   26%
Unpacking  [#########---------------------------]   27%
Unpacking  [##########--------------------------]   28%
Unpacking  [##########--------------------------]   29%
Unpacking  [###########-------------------------]   30%
Unpacking  [###########-------------------------]   31%
Unpacking  [###########-------------------------]   32%
Unpacking  [###########-------------------------]   33%
Unpacking  [############------------------------]   33%
Unpacking  [############------------------------]   34%
Unpacking  [############------------------------]   35%
Unpacking  [#############-----------------------]   36%
Unpacking  [#############-----------------------]   37%
Unpacking  [#############-----------------------]   38%
Unpacking  [##############----------------------]   39%
Unpacking  [##############----------------------]   40%
Unpacking  [##############----------------------]   41%
Unpacking  [###############---------------------]   41%
Unpacking  [###############---------------------]   42%
Unpacking  [###############---------------------]   43%
Unpacking  [###############---------------------]   44%
Unpacking  [################--------------------]   45%
Unpacking  [################--------------------]   46%
Unpacking  [#################-------------------]   47%
Unpacking  [#################-------------------]   48%
Unpacking  [#################-------------------]   49%
Unpacking  [##################------------------]   50%
Unpacking  [##################------------------]   51%
Unpacking  [##################------------------]   52%
Unpacking  [###################-----------------]   53%
Unpacking  [###################-----------------]   54%
Unpacking  [####################----------------]   55%
Unpacking  [####################----------------]   56%
Unpacking  [####################----------------]   57%
Unpacking  [####################----------------]   58%
Unpacking  [#####################---------------]   58%
Unpacking  [#####################---------------]   59%
Unpacking  [#####################---------------]   60%
Unpacking  [######################--------------]   61%
Unpacking  [######################--------------]   62%
Unpacking  [######################--------------]   63%
Unpacking  [#######################-------------]   64%
Unpacking  [#######################-------------]   65%
Unpacking  [#######################-------------]   66%
Unpacking  [########################------------]   66%
Unpacking  [########################------------]   67%
Unpacking  [########################------------]   68%
Unpacking  [########################------------]   69%
Unpacking  [#########################-----------]   70%
Unpacking  [#########################-----------]   71%
Unpacking  [##########################----------]   72%
Unpacking  [##########################----------]   73%
Unpacking  [##########################----------]   74%
Unpacking  [###########################---------]   75%
Unpacking  [###########################---------]   76%
Unpacking  [###########################---------]   77%
Unpacking  [############################--------]   78%
Unpacking  [############################--------]   79%
Unpacking  [#############################-------]   80%
Unpacking  [#############################-------]   81%
Unpacking  [#############################-------]   82%
Unpacking  [#############################-------]   83%
Unpacking  [##############################------]   83%
Unpacking  [##############################------]   84%
Unpacking  [##############################------]   85%
Unpacking  [###############################-----]   86%
Unpacking  [###############################-----]   87%
Unpacking  [###############################-----]   88%
Unpacking  [################################----]   89%
Unpacking  [################################----]   90%
Unpacking  [################################----]   91%
Unpacking  [#################################---]   91%
Unpacking  [#################################---]   92%
Unpacking  [#################################---]   93%
Unpacking  [#################################---]   94%
Unpacking  [##################################--]   95%
Unpacking  [##################################--]   96%
Unpacking  [###################################-]   97%
Unpacking  [###################################-]   98%
Unpacking  [###################################-]   99%
Unpacking  [####################################]  100%
Library Manager: ArduinoJson-esphomelib @ 5.13.3 has been installed!
Library Manager: Installing git+https://github.com/SwiCago/HeatPump
git version 2.25.1
Clone in '/root/.platformio/.cache/tmp/pkg-installing-cvdg7aat' in corso...
Library Manager: HeatPump @ 1.0.0+sha.4c3e51f has been installed!
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 2.0.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266WiFi> 1.0
|-- <AsyncMqttClient-esphome> 0.8.6
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <HeatPump> 1.0.0+sha.4c3e51f
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/heatpump-camera/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/binary_sensor/filter.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/climate/climate.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/climate/climate_mode.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/climate/climate_traits.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/dht/dht.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/esp8266/core.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/esp8266/gpio.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/esp8266/preferences.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/json/json_util.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/mdns/mdns_esp32_arduino.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/mdns/mdns_esp_idf.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/mitsubishi_heatpump/espmhp.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/mqtt/custom_mqtt_device.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/mqtt/mqtt_binary_sensor.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/mqtt/mqtt_client.cpp.o
Compiling .pioenvs/heatpump-camera/src/esphome/components/mqtt/mqtt_climate.cpp.o
src/esphome/components/mitsubishi_heatpump/espmhp.cpp: In member function 'void MitsubishiHeatPump::hpSettingsChanged()':
src/esphome/components/mitsubishi_heatpump/espmhp.cpp:261:17: error: call of overloaded 'delay(int)' is ambiguous
         delay(10);
                 ^
src/esphome/components/mitsubishi_heatpump/espmhp.cpp:261:17: note: candidates are:
In file included from .piolibdeps/heatpump-camera/ESPAsyncWebServer-esphome/src/ESPAsyncWebServer.h:24:0,
                 from src/esphome/components/web_server_base/web_server_base.h:9,
                 from src/esphome/components/captive_portal/captive_portal.h:10,
                 from src/esphome.h:5,
                 from src/esphome/components/mitsubishi_heatpump/espmhp.h:20,
                 from src/esphome/components/mitsubishi_heatpump/espmhp.cpp:20:
/root/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/Arduino.h:190:6: note: void delay(long unsigned int)
 void delay(unsigned long);
      ^
In file included from src/esphome/components/binary_sensor/automation.h:7:0,
                 from src/esphome.h:2,
                 from src/esphome/components/mitsubishi_heatpump/espmhp.h:20,
                 from src/esphome/components/mitsubishi_heatpump/espmhp.cpp:20:
src/esphome/core/hal.h:39:6: note: void esphome::delay(uint32_t)
 void delay(uint32_t ms);
      ^
src/esphome/components/mitsubishi_heatpump/espmhp.cpp: In member function 'virtual void MitsubishiHeatPump::setup()':
src/esphome/components/mitsubishi_heatpump/espmhp.cpp:472:39: error: request for member 'make_preference' in 'esphome::global_preferences', which is of pointer type 'esphome::ESPPreferences*' (maybe you meant to use '->' ?)
     cool_storage = global_preferences.make_preference<uint8_t>(this->get_object_id_hash() + 1);
                                       ^
src/esphome/components/mitsubishi_heatpump/espmhp.cpp:472:62: error: expected primary-expression before '>' token
     cool_storage = global_preferences.make_preference<uint8_t>(this->get_object_id_hash() + 1);
                                                              ^
src/esphome/components/mitsubishi_heatpump/espmhp.cpp:473:39: error: request for member 'make_preference' in 'esphome::global_preferences', which is of pointer type 'esphome::ESPPreferences*' (maybe you meant to use '->' ?)
     heat_storage = global_preferences.make_preference<uint8_t>(this->get_object_id_hash() + 2);
                                       ^
src/esphome/components/mitsubishi_heatpump/espmhp.cpp:473:62: error: expected primary-expression before '>' token
     heat_storage = global_preferences.make_preference<uint8_t>(this->get_object_id_hash() + 2);
                                                              ^
src/esphome/components/mitsubishi_heatpump/espmhp.cpp:474:39: error: request for member 'make_preference' in 'esphome::global_preferences', which is of pointer type 'esphome::ESPPreferences*' (maybe you meant to use '->' ?)
     auto_storage = global_preferences.make_preference<uint8_t>(this->get_object_id_hash() + 3);
                                       ^
src/esphome/components/mitsubishi_heatpump/espmhp.cpp:474:62: error: expected primary-expression before '>' token
     auto_storage = global_preferences.make_preference<uint8_t>(this->get_object_id_hash() + 3);
                                                              ^
Compiling .pioenvs/heatpump-camera/src/esphome/components/mqtt/mqtt_component.cpp.o
*** [.pioenvs/heatpump-camera/src/esphome/components/mitsubishi_heatpump/espmhp.cpp.o] Error 1
========================= [FAILED] Took 13.80 seconds =========================`

Thx for your time

**Comment by davidmerrique** [comment]
@geoffdavis Looks like it's fixed in the develop branch, but not in the master branch.

**Comment by geoffdavis** [comment]
That's what I get for trying to do this from an iPad in an airport lounge. Let me cut a new release.

**Comment by geoffdavis** [comment]
OK should be there in 2.3.2

**Comment by davidmerrique** [comment]
@geoffdavis Thanks so much
