### ISSUE TITLE
Not able to set temperature in Home Assistant

### ISSUE THREAD

**Issue by davidmerrique** [geoffdavis/esphome-mitsubishiheatpump#48]
Hi, I'm having a problem with 2 of my Wemos D1 Minis. 

I'm not seeing any target temperature in HA. 

![image](https://user-images.githubusercontent.com/867522/138614485-08bb224b-9db5-44ec-9032-d6101958c54a.jpeg)

I have it working with 3 units, but 2 units aren't working. 

Could this be a difference between my ESP8266? 

The 3 that work perfectly are these:

IZOKEE Development Board for ESP8266 ESP-12F 4M Bytes WLAN WiFi Internet Development Board Compatible with Arduino (Pack of 3) https://smile.amazon.com/dp/B076F53B6S/ref=cm_sw_r_cp_api_glt_fabc_6EJMYZJHQGA6H46PY2SW?_encoding=UTF8&psc=1

And the 2 that aren't working are these:

WLAN WiFi Internet Development Board D1 Mini NodeMcu Lua 4M Bytes Development Module Base on ESP8266 ESP-12F for Arduino Compatible with WeMos D1 Mini (2PCS) https://smile.amazon.com/dp/B07W8ZQY62/ref=cm_sw_r_cp_api_glt_fabc_NXM7W75RCKJ4QFZ9SYWT?_encoding=UTF8&psc=1

I'm not seeing any difference between these, but maybe that's the problem?

Thanks!

**Comment by earwin** [comment]
@davidmerrique you can try resetting your D1s once or twice (see #49)
Though my setup has some resistors there I think (as Geoff suggests).

**Comment by jeffborg** [comment]
I have had a d1 mini in my air con for years now, But I'm just using a TTL level shifter. Only just recently switched firmware to esphome and has been flawless over these years.

**Comment by geoffdavis** [comment]
The reisistors set up as voltage dividers are indeed the poor man’s level
shifter. The MOSFET-based level shifters are the better approach. At the
4800 bps data rate of this serial line, even the cheap ones work fine.

Glad to hear that the mystery has been solved. Note that some batches of
chips may have slightly higher 3.3v logic output than others which would
explain the case where some D1 minis work and others don’t. Use the voltage
divider or level shifters and take the guesswork out of it.

**Comment by jamescadd** [comment]
I didn't realize a proper MOSFET level shifter was an option, and I need to add some level shifting. Any chance you could point to some that are known to work @geoffdavis ?

**Comment by geoffdavis** [comment]
Any of the IIC or I2C level shifters on Amazon or AliExpress will do the
trick. The FETs don’t need to have high frequency switching for this
application. Adafruit also has one.

This would work: KeeYees 10pcs 4 Channels IIC I2C Logic Level Converter
Bi-Directional Module 3.3V to 5V Shifter for Arduino (Pack of 10)
https://www.amazon.com/dp/B07LG646VS/ref=cm_sw_r_cp_api_glt_fabc_KCG7JGSXX1CN60HYA1FB
