### ISSUE TITLE
No serial connection to Wemo D1 Mini V3

### ISSUE THREAD

**Issue by jb123567** [geoffdavis/esphome-mitsubishiheatpump#54]
I have been trying to get this working with considerable issues. I have installed on the Wemo D1 Mini V3 then removed the pin described in the Home Assistant. It doesn't appear that the device is getting the serial connection and communicate with the unit.

Any suggestions?

**Comment by geoffdavis** [comment]
Depending on the version of your Wemos D1 mini, you may need to use a logic level converter or the voltage divider method that is mentioned in the README. It's somewhat of a crapshoot as to whether a given D1 mini requires the logic level conversion, so if you're making more than one, just use a logic level converter to be on the safe side.

The three ghetto-fab ESP-01S units I have driving my heatpumps are all using the voltage divider method.
