### ISSUE TITLE
UI slow to update?

### ISSUE THREAD

**Issue by jamescadd** [geoffdavis/esphome-mitsubishiheatpump#6]
Hello, not sure if this is an actual issue, but when I change mode from off to cool, the machine reacts immediately and the LED turns on showing that the command was successful.  However the thermostat UI (I'm using simple thermostat) can take ~15 seconds to reflect that change.  Is there a polling interval that can be adjustment to make it more responsive, or could this be an issue with the UI component?

**Comment by pgenera** [comment]
the code publishes updates when it receives them from the minisplit; it
takes about 30 seconds for the minisplit to send an update after it gets a
new configuration. I've got a patch that optimistically sends an update
immediately; I'll send a PR once my corporate overlords approve it.

>

**Comment by pgenera** [comment]
aforementioned PR: #7

**Comment by geoffdavis** [comment]
Merged PR #7 should take care of this. Note that it's blindly issuing the command now and then updating state, but eventually it will sync it's state with the unit if the command didn't actually take effect.
