### ISSUE TITLE
Compatibility with Flow Temp. Controller

### ISSUE THREAD

**Issue by rosscullen** [geoffdavis/esphome-mitsubishiheatpump#67]
Hi all, wanted to check if anyone has tried this with a Mitsubishi Flow Temp. Controller? Model PAC-IF062B0E. It has a CN105 Port and I've managed to flash a D1 mini and get it to power from the CN105 Port but not receiving any valid data. Was hoping for basic readings such as temperatures etc. 

I'm told it works with MELCloud. It uses the  Ecodan FTC5 control panel. 

Any thoughts or suggestions greatly appreciated :-D

**Comment by geoffdavis** [comment]
I would check with the SwiCago library, particularly this ticket: https://github.com/SwiCago/HeatPump/issues/39

It looks like @lekobob has done some additional work with both a fork of this repository and the SwiCago repository to handle a ducted mini-split unit, and may have some ideas on the low level protocol decode.
