### ISSUE TITLE
Changing fan mode causes unit to turn off

### ISSUE THREAD

**Issue by jamescadd** [geoffdavis/esphome-mitsubishiheatpump#9]
I've been trying the different options for fan mode for the units I have (MSZ-GL09NA) and it seems that choosing any setting other than Auto causes them to shut off.  I would guess the issue is with the core library but wanted to see if anyone else here sees the same.

**Comment by villevirtanen** [comment]
This issue is reproducible also with my unit (MSZ-GE35VA).

**Comment by geoffdavis** [comment]
I think this popped up in the recent optimistic status update change. I’ll see if I can track it down.

**Comment by geoffdavis** [comment]
I believe this was fixed in GH-12. Please test and re-open if I'm mistaken.

**Comment by jamescadd** [comment]
I'm late to comment, but just tested and this is fixed on MSZ-GL09NA.
