### ISSUE TITLE
Add extra options via different components

### ISSUE THREAD

**Issue by brywithawhy** [geoffdavis/esphome-mitsubishiheatpump#90]
Just had a MSZ-AP71VGD Indoor Unit installed which has Powerful and Eco Modes, as well as Horizontal vane control and a Night Mode (which I don't know what it does yet).

I understand the climate component in ESPHome is limited, however I've previously used a similar integration for my Panasonic units from https://github.com/DomiStyle/esphome-panasonic-ac which has the ability to use select components for vane position/swing, a switch for the Eco Mode, and uses the "Preset" menu for the climate component to control Powerful/Quiet modes.

Is this something that could be added to this component to get this functionality working for Mitsubishi Units?

**Comment by Smandurlo** [comment]
I control my mitsubishi ACs with tasmota and I have the possibility to use any combination of hvac mode/fan speed/swing mode. It can be orizzontal, vertical and so on. No problem to add extra mode like your night, powerful, eco... I have quiet too.
Everything is managed with mqtt. Will it work with esphome and mqtt instead of the api? I am very new to esphome and I have some difficulties to understand how it work.

I am attracted to switch to esphome because it has the possibility to use an external temperature sensor averriding the AC internal one and, afaik, I cannot do it with tasmota.

If you know more about mqtt in esphome we could work on it.

**Comment by brywithawhy** [comment]
> I control my mitsubishi ACs with tasmota and I have the possibility to use any combination of hvac mode/fan speed/swing mode. It can be orizzontal, vertical and so on. No problem to add extra mode like your night, powerful, eco... I have quiet too. Everything is managed with mqtt.
> 

Have you got any info on your tasmota setup? I'm going to ditch esphome because there's just too little features and I have strange behaviour on occasion.

**Comment by Smandurlo** [comment]
I am interested in the external temperature sensor, it is not possible afaik with tasmota. Other than that, they have zero problem. What is the strange behaviour you have?

For tasmota you need to compile your firmware adding the mitsubishi ac component and flash your esp. Than you make your configuration with mqtt.

**Comment by Smandurlo** [comment]
![Screenshot_2023-07-16-15-18-31-967_io homeassistant companion android-edit](https://github.com/geoffdavis/esphome-mitsubishiheatpump/assets/36647269/9a56b82a-c1b5-4f7d-a5d3-57f7e7657d6b)

Just a screenshot of the code. You can add anything you need according with your settings

**Comment by brywithawhy** [comment]
Thanks for the info @Smandurlo
Guess I've got no reason to stay with this esphome version now.

**Comment by Smandurlo** [comment]
Yes, I tried esphome and there are some very good things, but I still prefer tasmota.

**Comment by geoffdavis** [comment]
Interesting, the Tasmota Mitsubishi AC component didn't exist when I wrote this integration years ago. Thanks for the pointer.

The Climate integration in ESPHome is limited to a list of predefined actions in the API, detailed here: https://esphome.io/api/classesphome_1_1climate_1_1_climate_call.html

There's no way through Home Assistant to add anything else without expanding the whole API.

**Comment by brywithawhy** [comment]
They could be added as separate switches or input selects along side the climate component.
That's how the Panasonic one works from the link I posted above.
